// Blocks Beyond the Stars — Copyright (c) 2026 Justus Dütscher & Marcel Dütscher (JuMaVe Games)
// SPDX-License-Identifier: AGPL-3.0-or-later
// This file is part of Blocks Beyond the Stars. See LICENSE for the full AGPL-3.0 text.
using System.Diagnostics;

namespace BlocksBeyondTheStars.WorldHost;

/// <summary>
/// Starts/stops one dedicated-server container per world. Abstracted so the orchestrator's allocation
/// logic is testable without Docker; production uses <see cref="DockerCliLauncher"/>.
/// </summary>
public interface IInstanceLauncher
{
    /// <summary>Starts the instance for a world and returns the container id (throws on failure).</summary>
    string Start(WorldRecord world);

    /// <summary>Stops the container (triggering the server's clean drain+save via SIGTERM). Idempotent.</summary>
    void Stop(string containerId);

    /// <summary>Whether the container is still running — false once an idle shutdown has exited it.</summary>
    bool IsRunning(string containerId);
}

/// <summary>
/// Docker-CLI launcher: shells out to <c>docker</c> with <see cref="ProcessStartInfo.ArgumentList"/>
/// (argv-level, no shell interpolation), so no value can smuggle extra arguments in. Defense in depth on
/// top of that: everything user-influenced that reaches this class is already validated/generated by the
/// registry (world ids are server-generated hex; the display name is passed only as an ENV VALUE).
///
/// Container shape per world:
///  - name <c>bbs-world-&lt;id&gt;</c>, volume <c>bbs-world-&lt;id&gt;-saves</c> mounted at /app/saves
///  - <c>--restart=no</c> — REQUIRED: the instance exits itself on idle (BBS_IDLE_SHUTDOWN_MINUTES);
///    an auto-restart policy would wake it right back up and defeat sleeping
///  - one stable host port published as udp (native gameplay) AND tcp (WS gateway; /status health probe)
///  - caddy-docker-proxy labels so <c>w-&lt;id&gt;.&lt;BaseDomain&gt;</c> routes wss onto the gateway
/// </summary>
public sealed class DockerCliLauncher : IInstanceLauncher
{
    private readonly WorldHostConfig _config;

    public DockerCliLauncher(WorldHostConfig config) => _config = config;

    public string Start(WorldRecord world)
    {
        var args = new List<string>
        {
            "run", "-d",
            "--name", $"bbs-world-{world.Id}",
            "--restart=no",
            "--stop-timeout", "60", // match the compose stop_grace_period: drain + save needs time
            "--network", _config.DockerNetwork,
            "-p", $"{world.HostPort}:31415/udp",
            "-p", $"127.0.0.1:{world.HostPort}:31415/tcp", // tcp side only for the local /status probe; public wss goes through Caddy
            "-v", $"bbs-world-{world.Id}-saves:/app/saves",
            "-e", $"BBS_WORLD={world.Id}",
            "-e", $"BBS_SERVER_NAME={world.DisplayName}",
            "-e", $"BBS_MAX_PLAYERS={_config.MaxPlayersPerWorld}",
            "-e", $"BBS_IDLE_SHUTDOWN_MINUTES={_config.IdleShutdownMinutes}",
            "-e", $"BBS_JOIN_TOKEN_SECRET={world.JoinSecret}",
            "-e", $"BBS_WORLD_OWNER={world.OwnerAccountId}",
            "-e", "BBS_ENABLE_WEBSOCKET=true",
            "-e", "BBS_WEBSOCKET_BIND=+",
            "-l", $"caddy=w-{world.Id}.{_config.BaseDomain}",
            "-l", "caddy.reverse_proxy={{upstreams 31415}}",
            _config.ServerImage,
        };

        var (exitCode, stdout, stderr) = Run(args);
        if (exitCode != 0)
        {
            throw new InvalidOperationException($"docker run failed for world {world.Id}: {stderr.Trim()}");
        }

        return stdout.Trim(); // container id
    }

    public void Stop(string containerId)
    {
        if (string.IsNullOrEmpty(containerId))
        {
            return;
        }

        Run(new List<string> { "stop", containerId }); // best effort; "no such container" is fine
    }

    public bool IsRunning(string containerId)
    {
        if (string.IsNullOrEmpty(containerId))
        {
            return false;
        }

        var (exitCode, stdout, _) = Run(new List<string> { "inspect", "--format", "{{.State.Running}}", containerId });
        return exitCode == 0 && stdout.Trim() == "true";
    }

    private static (int ExitCode, string Stdout, string Stderr) Run(List<string> args)
    {
        var psi = new ProcessStartInfo("docker")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var a in args)
        {
            psi.ArgumentList.Add(a);
        }

        using var proc = Process.Start(psi) ?? throw new InvalidOperationException("Failed to start docker CLI.");
        string stdout = proc.StandardOutput.ReadToEnd();
        string stderr = proc.StandardError.ReadToEnd();
        proc.WaitForExit(120_000);
        return (proc.HasExited ? proc.ExitCode : -1, stdout, stderr);
    }
}
