# /// script
# requires-python = ">=3.11"
# dependencies = ["requests"]
# ///
"""Export all PUBLISHED blog posts into the devblog markdown files.

Fetches every published post (DE -> devblog-artikel.md, EN ->
devblog-artikel-en.md), converts its rich content back to markdown and
appends it under an "already published" section including category and the
live publish date. Together with the draft articles this makes the two md
files the single point of truth for the blog.

Safe to re-run: the exported section is replaced, not duplicated.

Usage (from tools/devblog/):
  uv run export_posts.py
"""

from __future__ import annotations

import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import requests

SCRIPT_DIR = Path(__file__).resolve().parent
ENV_FILE = SCRIPT_DIR / ".env"
API = "https://www.wixapis.com"

FILES = {
    "de": SCRIPT_DIR / "devblog-artikel.md",
    "en": SCRIPT_DIR / "devblog-artikel-en.md",
}
SECTION_HEADER = {
    "de": "# Bereits veröffentlicht (Export aus dem Wix-Blog)",
    "en": "# Already published (exported from the Wix blog)",
}
LABELS = {
    "de": ("Kategorie", "Veröffentlicht"),
    "en": ("Category", "Published"),
}


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip()
    return env


def main() -> None:
    env = load_env()
    session = requests.Session()
    session.headers.update({
        "Authorization": env["WIX_API_KEY"],
        "wix-site-id": env["WIX_SITE_ID"],
        "Content-Type": "application/json",
    })

    r = session.get(f"{API}/blog/v3/categories?paging.limit=100", timeout=60)
    r.raise_for_status()
    cat_label = {c["id"]: c["label"] for c in r.json()["categories"]}

    posts, offset = [], 0
    while True:
        r = session.get(
            f"{API}/blog/v3/posts?paging.limit=100&paging.offset={offset}", timeout=60)
        r.raise_for_status()
        page = r.json()["posts"]
        posts.extend(page)
        if len(page) < 100:
            break
        offset += 100
    posts.sort(key=lambda p: p["firstPublishedDate"])
    print(f"{len(posts)} published posts fetched.")

    sections: dict[str, list[str]] = {"de": [], "en": []}
    for post in posts:
        lang = post.get("language", "de")
        if lang not in sections:
            print(f"  !! unexpected language {lang!r}: {post['title'][:50]} — skipped")
            continue

        r = session.get(
            f"{API}/blog/v3/posts/{post['id']}?fieldsets=RICH_CONTENT", timeout=60)
        r.raise_for_status()
        rich = r.json()["post"].get("richContent")
        if not rich:
            print(f"  !! no rich content: {post['title'][:50]} — skipped")
            continue

        r = session.post(
            f"{API}/ricos/v1/ricos-document/convert/from-ricos",
            json={"document": rich, "targetFormat": "MARKDOWN"}, timeout=60)
        if not r.ok:
            sys.exit(f"from-ricos failed for {post['title']!r}: "
                     f"HTTP {r.status_code}: {r.text[:300]}")
        body = r.json().get("markdown", "").strip()

        cat_key, date_key = LABELS[lang]
        cats = ", ".join(cat_label.get(cid, cid) for cid in post.get("categoryIds", []))
        date = post["firstPublishedDate"][:16].replace("T", " ") + " UTC"
        sections[lang].append(
            f"## {post['title']}\n\n"
            f"**{cat_key}:** {cats}\n\n"
            f"**{date_key}:** {date}\n\n"
            f"{body}\n\n---\n"
        )
        print(f"  exported [{lang}] {post['title'][:60]}")
        time.sleep(0.3)

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    for lang, path in FILES.items():
        text = path.read_text(encoding="utf-8")
        marker = SECTION_HEADER[lang]
        if marker in text:  # replace previous export
            text = text[: text.index(marker)].rstrip() + "\n"
        block = (f"\n\n{marker}\n\n"
                 f"_Auto-generated by export_posts.py — last export {stamp}. "
                 f"Do not edit here; edit in the blog and re-export._\n\n---\n\n"
                 + "\n".join(sections[lang]))
        path.write_text(text.rstrip() + block, encoding="utf-8")
        print(f"{path.name}: {len(sections[lang])} published posts written.")


if __name__ == "__main__":
    main()
